// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XLQaCm5MguYhHxnTLig77XfqzmYLpsE',
    appId: '1:825030845854:web:d4faa23bc645047a0fe28f',
    messagingSenderId: '825030845854',
    projectId: 'social-connect-app-dd349',
    authDomain: 'social-connect-app-dd349.firebaseapp.com',
    storageBucket: 'social-connect-app-dd349.appspot.com',
    measurementId: 'G-6E7CCQJSR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWzqblCQWO5QGgYZ8BjKwH8rpuqzGXvVA',
    appId: '1:825030845854:android:6702b843faccda040fe28f',
    messagingSenderId: '825030845854',
    projectId: 'social-connect-app-dd349',
    storageBucket: 'social-connect-app-dd349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1C3lUwG2t5Zy1ddYcYVXm4NdNNw8z_Q4',
    appId: '1:825030845854:ios:82e4de286d7cb7970fe28f',
    messagingSenderId: '825030845854',
    projectId: 'social-connect-app-dd349',
    storageBucket: 'social-connect-app-dd349.appspot.com',
    iosBundleId: 'com.example.socialConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1C3lUwG2t5Zy1ddYcYVXm4NdNNw8z_Q4',
    appId: '1:825030845854:ios:82e4de286d7cb7970fe28f',
    messagingSenderId: '825030845854',
    projectId: 'social-connect-app-dd349',
    storageBucket: 'social-connect-app-dd349.appspot.com',
    iosBundleId: 'com.example.socialConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XLQaCm5MguYhHxnTLig77XfqzmYLpsE',
    appId: '1:825030845854:web:92cc7bbc9e238be60fe28f',
    messagingSenderId: '825030845854',
    projectId: 'social-connect-app-dd349',
    authDomain: 'social-connect-app-dd349.firebaseapp.com',
    storageBucket: 'social-connect-app-dd349.appspot.com',
    measurementId: 'G-V5PN7ZNNVR',
  );
}
